// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXWe7_DSaxxo10h22W6InyXV9PUjGvLh8',
    appId: '1:1087180467328:web:410dd2b43be42034914a65',
    messagingSenderId: '1087180467328',
    projectId: 'food-delivery-management-bc5eb',
    authDomain: 'food-delivery-management-bc5eb.firebaseapp.com',
    storageBucket: 'food-delivery-management-bc5eb.firebasestorage.app',
    measurementId: 'G-G29Z1QFRE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8-G6lVtQSVty9FgRxQfA2OmLe-8J_cT8',
    appId: '1:1087180467328:android:d20e7e71c08f369d914a65',
    messagingSenderId: '1087180467328',
    projectId: 'food-delivery-management-bc5eb',
    storageBucket: 'food-delivery-management-bc5eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqrc3rx0HM5MnUG0aKV7HJO4G8stCcNw',
    appId: '1:1087180467328:ios:969a0e83e54e17d7914a65',
    messagingSenderId: '1087180467328',
    projectId: 'food-delivery-management-bc5eb',
    storageBucket: 'food-delivery-management-bc5eb.firebasestorage.app',
    iosClientId: '1087180467328-2v5qqfp1ifbkvj2km5q1dvohq1d4pq9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.appb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqrc3rx0HM5MnUG0aKV7HJO4G8stCcNw',
    appId: '1:1087180467328:ios:969a0e83e54e17d7914a65',
    messagingSenderId: '1087180467328',
    projectId: 'food-delivery-management-bc5eb',
    storageBucket: 'food-delivery-management-bc5eb.firebasestorage.app',
    iosClientId: '1087180467328-2v5qqfp1ifbkvj2km5q1dvohq1d4pq9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.appb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXWe7_DSaxxo10h22W6InyXV9PUjGvLh8',
    appId: '1:1087180467328:web:3181a7f78f9962dd914a65',
    messagingSenderId: '1087180467328',
    projectId: 'food-delivery-management-bc5eb',
    authDomain: 'food-delivery-management-bc5eb.firebaseapp.com',
    storageBucket: 'food-delivery-management-bc5eb.firebasestorage.app',
    measurementId: 'G-7PDG9D77CD',
  );

}