// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnAdD2tZzzddjdI83P6joshrmM57DbYA',
    appId: '1:19011937799:web:1bd076c1d5da70a25aeca2',
    messagingSenderId: '19011937799',
    projectId: 'fitness-managemnt',
    authDomain: 'fitness-managemnt.firebaseapp.com',
    storageBucket: 'fitness-managemnt.firebasestorage.app',
    measurementId: 'G-PBMDD5TFT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpVG8R1G9UFbfd4otpJqSrflJsofKtGDs',
    appId: '1:19011937799:android:ae9bd82f140b1f5a5aeca2',
    messagingSenderId: '19011937799',
    projectId: 'fitness-managemnt',
    storageBucket: 'fitness-managemnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7v8DJIy0cUkx0N1o99AEgb3U3CC7CQBk',
    appId: '1:19011937799:ios:dda29c7afc1805375aeca2',
    messagingSenderId: '19011937799',
    projectId: 'fitness-managemnt',
    storageBucket: 'fitness-managemnt.firebasestorage.app',
    iosClientId: '19011937799-a67q30672l074d0rr1etacmv8ov9vhjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7v8DJIy0cUkx0N1o99AEgb3U3CC7CQBk',
    appId: '1:19011937799:ios:dda29c7afc1805375aeca2',
    messagingSenderId: '19011937799',
    projectId: 'fitness-managemnt',
    storageBucket: 'fitness-managemnt.firebasestorage.app',
    iosClientId: '19011937799-a67q30672l074d0rr1etacmv8ov9vhjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnnAdD2tZzzddjdI83P6joshrmM57DbYA',
    appId: '1:19011937799:web:a5f291084e3b4d945aeca2',
    messagingSenderId: '19011937799',
    projectId: 'fitness-managemnt',
    authDomain: 'fitness-managemnt.firebaseapp.com',
    storageBucket: 'fitness-managemnt.firebasestorage.app',
    measurementId: 'G-DXMH040X9H',
  );

}